### ISSUE TITLE
Сделать возможность указывать путь к директории с проектами

### ISSUE THREAD

**Issue by ismd** [st7art22/gulp-projects-run-tasks#3]

**Comment by st7art22** [comment]
gulp-dev/routes.js  разве не это?
или имелось ввиду, что-то другое?

**Comment by ismd** [comment]
Не, я имел ввиду, что сейчас необходимо запускать gulp, находясь в директории с проектами. Соответственно gulpfile.js и другие файлы должны лежать здесь же. Мне бы хотелось, чтобы рабочая копия этого репозитория со всеми файлами (gulpfile.js, ...) лежала где-то в другом месте, а при вызове я мог бы как-нибудь указывать путь к директории с проектами.

**Comment by st7art22** [comment]
у таков добавил возможность указать путь до директории проекта.
